function newCreationFilterData(memescopePage) {
    return {
        Title: memescopePage?.mainHeader?.filters?.newcreation?.newcreationsfilter,
        FilterInput: [
            {
                id: "1",
                name: memescopePage?.mainHeader?.filters?.newcreation?.top10holders,
                title: "top10holders",
                type: "checkbox",
            },
            {
                id: "2",
                name: memescopePage?.mainHeader?.filters?.newcreation?.withatleast1social,
                title: "withatleast1social",
                type: "checkbox",
            },
        ],
        FromToFilter: [
            {
                id: "3",
                title: "progress",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bypumpprogress,
                firstInputName: "Min",
                firstInputIcon: "%",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "4",
                title: "Holders",
                name: memescopePage?.mainHeader?.filters?.newcreation?.byholderscount,
                firstInputName: "Min",
                firstInputIcon: "%",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "5",
                title: "holding",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bydevholding,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "6",
                title: "Snipers",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bysnipers,
                firstInputName: "Min",
                firstInputIcon: "$",
                secondInputName: "Max",
                secondInputIcon: "$",
                type: "number",
            },
            {
                id: "7",
                title: "Age",
                name: memescopePage?.mainHeader?.filters?.newcreation?.byage,
                firstInputName: "Min",
                firstInputIcon: "$",
                secondInputName: "Max",
                secondInputIcon: "$",
                type: "number",
            },
            {
                id: "8",
                title: "Liquidity",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bycurrentliquidity,
                firstInputName: "Min",
                firstInputIcon: "$",
                secondInputName: "Max",
                secondInputIcon: "$",
                type: "number",
            },
            {
                id: "9",
                title: "Volume",
                name: memescopePage?.mainHeader?.filters?.newcreation?.byvolume,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "10",
                title: "MKT",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bymCap,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "11",
                title: "TXNS",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bytx,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "12",
                title: "Buys",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bybuys,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
            {
                id: "13",
                title: "Sells",
                name: memescopePage?.mainHeader?.filters?.newcreation?.bysells,
                firstInputName: "Min",
                firstInputIcon: "",
                secondInputName: "Max",
                secondInputIcon: "",
                type: "number",
            },
        ]
    }
};

export { newCreationFilterData };