import "./globals.css";
import localFont from "next/font/local";
import { Poppins, Space_Grotesk } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import PagesLayout from "./PagesLayout";
import { Toaster } from "react-hot-toast";
import { headers } from "next/headers";
import Providers from "./redux/provider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// Google Font - Space Grotesk
const spaceGrotesk = Space_Grotesk({
    subsets: ["latin"],
    variable: "--font-space-grotesk",
    weight: ["300", "400", "500", "600", "700"], // Add the weights you need
});

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["400", "600", "700"], // Add the weights you need
});

export const metadata = {
    title: "Nexa Pro",
    description: "Generated by nexa team",
};

export default function RootLayout({ children }) {
    const cookies = headers().get("cookie");

    return (
        <html lang="en">
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable}  ${poppins.variable} ${spaceGrotesk.variable} antialiased`}
            >
                    <Providers>
                        <div className="flex">
                            <div className="w-auto">
                                <Sidebar />
                            </div>
                            <PagesLayout childrens={children} />
                            <Toaster
                                position="top-right"
                                reverseOrder={false}
                            />
                        </div>
                    </Providers>
            </body>
        </html>
    );
}
